### ISSUE TITLE
[react] refresh page in dark mode, giscus element with theme=dark property but the iframe element load light.css

### ISSUE THREAD

**Issue by zhangwh754** [giscus/giscus-component#1952] opened 2024-01-12 08:37 UTC
If refresh page when giscus-component in viewport, the theme will render correct.
but if refresh page when giscus-component out of viewport, the problem will occur.

current condition:
![image](https://github.com/giscus/giscus-component/assets/80935439/88df12e4-ed06-42d2-a6aa-d8bc1fb0c5a6) 
![image](https://github.com/giscus/giscus-component/assets/80935439/ca66a5b5-7142-4bb2-9d3b-28ed21b17235)

expext:
![image](https://github.com/giscus/giscus-component/assets/80935439/dd9e9c79-38a7-4e33-add2-e858103c48c1)

I notice previous Issue #1152 ,but after my try, this problem both occur when lazing and eager.

my code
```tsx
'use client'

import { useEffect, useState } from 'react'
import Giscus from '@giscus/react'
import { shallow } from 'zustand/shallow'
import { useThemeStore } from 'stores/theme-store'

export default function SiteComments(props: { slug: string }) {
  const isDark = useThemeStore(state => state.isDark, shallow)

  const [mounted, setMounted] = useState(false)
  useEffect(() => setMounted(true), [])

  if (!mounted) return null

  return (
    <Giscus
      id={props.slug}
      repo="zhangwh754/blog-comments"
      repoId="R_kgDOLBAVFw"
      category="Announcements"
      categoryId="DIC_kwDOLBAVF84CcNVV"
      mapping="title"
      strict="0"
      reactionsEnabled="1"
      emitMetadata="1"
      inputPosition="top"
      theme={isDark ? 'dark' : 'light'}
      lang="zh-CN"
      loading="lazy"
    />
  )
}

````

**Comment by BinarySenseiii** [comment] 2024-04-29 01:27
@zhangwh754 When the theme changes, you need to rerender the component. Simply add a 'key' prop to the Giscus component with the theme value. This way, whenever the theme changes, it will update accordingly like so 

```
<Giscus
     key={isDark}
     repo="zhangwh754/blog-comments"
     repoId="R_kgDOLBAVFw"
 />
```

**Comment by laymonage** [comment] 2024-12-15 09:59
I can't reproduce it with the incomplete sample code. It's likely because of how the theme is stored and retrieved in your component. Check whether `isDark` has a different value on the initial render.

Closing for now, I can reopen if you can provide a reproducible example. Thanks.

**Closed by laymonage** 2024-12-15 09:59 UTC
